/**
 * Deve permanecer alinhado com `PULL_TABLES` em `sync/sync-engine.ts` (ordem FK + colunas).
 */
import { EMPRESAS_CONFIG_PG_PULL_COLUMNS } from './empresas-config-mirror'

export type PullTableDef = { table: string; columns: string[] }

export const PULL_TABLES: PullTableDef[] = [
  { table: 'empresas', columns: ['id', 'nome', 'cnpj', 'created_at'] },
  { table: 'usuarios', columns: ['id', 'empresa_id', 'nome', 'login', 'senha_hash', 'role', 'modulos_json', 'created_at'] },
  { table: 'empresas_config', columns: [...EMPRESAS_CONFIG_PG_PULL_COLUMNS] },
  { table: 'categorias', columns: ['id', 'empresa_id', 'nome', 'parent_id', 'nivel', 'ordem', 'ativo', 'created_at'] },
  { table: 'marcas', columns: ['id', 'empresa_id', 'nome', 'ativo', 'created_at', 'updated_at'] },
  {
    table: 'produtos',
    columns: [
      'id',
      'empresa_id',
      'codigo',
      'nome',
      'sku',
      'codigo_barras',
      'fornecedor_id',
      'categoria_id',
      'marca_id',
      'descricao',
      'imagem',
      'custo',
      'markup',
      'preco',
      'unidade',
      'controla_estoque',
      'estoque_minimo',
      'estoque_atual',
      'ativo',
      'ncm',
      'cfop',
      'cashback_ativo',
      'cashback_percentual',
      'permitir_resgate_cashback_no_produto',
      'cashback_observacao',
      'created_at',
      'updated_at',
    ],
  },
  {
    table: 'clientes',
    columns: ['id', 'empresa_id', 'nome', 'cpf_cnpj', 'telefone', 'email', 'endereco', 'observacoes', 'limite_credito', 'created_at'],
  },
  {
    table: 'fornecedores',
    columns: [
      'id',
      'empresa_id',
      'razao_social',
      'cnpj',
      'contato',
      'observacoes',
      'created_at',
      'tipo_cadastro',
      'nome_fantasia',
      'nome_responsavel',
      'inscricao_estadual',
      'inscricao_municipal',
      'indicador_contribuinte',
      'ativo',
      'fornecedor_principal',
      'categoria_fornecedor',
      'updated_at',
      'created_by',
      'updated_by',
      'telefone_principal',
      'telefone_secundario',
      'celular_whatsapp',
      'email_principal',
      'email_financeiro',
      'site',
      'nome_contato_comercial',
      'nome_contato_financeiro',
      'endereco_cep',
      'endereco_logradouro',
      'endereco_numero',
      'endereco_complemento',
      'endereco_bairro',
      'endereco_cidade',
      'endereco_estado',
      'endereco_pais',
      'endereco_referencia',
      'prazo_medio_pagamento',
      'condicao_pagamento_padrao',
      'limite_credito',
      'vendedor_representante',
      'segmento_fornecedor',
      'origem_fornecedor',
      'observacoes_comerciais',
      'produtos_servicos_fornecidos',
      'banco',
      'agencia',
      'conta',
      'tipo_conta',
      'chave_pix',
      'favorecido',
      'documento_favorecido',
      'regime_tributario',
      'retencoes_aplicaveis',
      'observacoes_fiscais',
      'tipo_operacao_comum',
      'natureza_fornecimento',
      'observacoes_internas',
      'tags',
      'bloqueio_compras',
      'motivo_bloqueio',
      'avaliacao_interna',
      'prazo_medio_entrega',
      'score_classificacao',
    ],
  },
  {
    table: 'estoque_movimentos',
    columns: [
      'id',
      'empresa_id',
      'produto_id',
      'tipo',
      'quantidade',
      'custo_unitario',
      'referencia_tipo',
      'referencia_id',
      'usuario_id',
      'created_at',
    ],
  },
  { table: 'caixas', columns: ['id', 'empresa_id', 'usuario_id', 'status', 'valor_inicial', 'aberto_em', 'fechado_em'] },
  { table: 'caixa_movimentos', columns: ['id', 'empresa_id', 'caixa_id', 'tipo', 'valor', 'motivo', 'usuario_id', 'created_at'] },
  {
    table: 'vendas',
    columns: [
      'id',
      'empresa_id',
      'caixa_id',
      'usuario_id',
      'cliente_id',
      'numero',
      'status',
      'subtotal',
      'desconto_total',
      'total',
      'troco',
      'venda_a_prazo',
      'data_vencimento',
      'created_at',
    ],
  },
  { table: 'venda_itens', columns: ['id', 'empresa_id', 'venda_id', 'produto_id', 'descricao', 'preco_unitario', 'quantidade', 'desconto', 'total'] },
  { table: 'pagamentos', columns: ['id', 'empresa_id', 'venda_id', 'forma', 'valor'] },
  {
    table: 'contas_receber',
    columns: [
      'id',
      'empresa_id',
      'venda_id',
      'cliente_id',
      'valor',
      'vencimento',
      'status',
      'recebido_em',
      'recebimento_caixa_id',
      'forma_recebimento',
      'usuario_recebimento_id',
      'created_at',
    ],
  },
  {
    table: 'venda_nfce',
    columns: [
      'venda_id',
      'numero_nfce',
      'status',
      'chave',
      'protocolo',
      'mensagem_sefaz',
      'xml_local_path',
      'xml_supabase_path',
      'created_at',
      'updated_at',
    ],
  },
  {
    table: 'venda_nfe',
    columns: [
      'venda_id',
      'modelo',
      'serie',
      'numero_nfe',
      'status',
      'chave',
      'protocolo',
      'mensagem_sefaz',
      'xml_local_path',
      'xml_supabase_path',
      'created_at',
      'updated_at',
    ],
  },
]

export const PULL_FISCAL_MERGE_TABLES = new Set(['venda_nfce', 'venda_nfe'])

export const PULL_TABLES_REPLACE = PULL_TABLES.filter(
  (t) => t.table !== 'empresas' && t.table !== 'usuarios' && !PULL_FISCAL_MERGE_TABLES.has(t.table)
)

export const PULL_TABLES_REPLACE_REVERSE = [...PULL_TABLES_REPLACE].reverse()
